### ISSUE TITLE
large tree sum of branch of length

### ISSUE THREAD

**Issue by jianshu93** [lucblassel/phylotree-rs#8]
Hi @lucblassel,

I want to calculate Unifrac distance (https://en.wikipedia.org/wiki/UniFrac) in parallel for a very large tree (3,000,000 tips), this is related to compute sum of branch length of some tip (determined by a metadata) and divided by sum of all Brach length in the tree, pairwise among samples. Each time a branch length of the tip to the root needs to to be computed. This should be a constant time operation using phylotree right.

Thanks,

Jianshu

**Comment by lucblassel** [comment]
Hello @jianshu93, 
as it stands, the `get_distance` and `get_path_to_root` functions that would be used to compute the sum of branch lengths between a given leaf and the root are not cached, so computing this sum for all tree leaves would probably scale in $\mathcal{O}(n\log n)$:  

```rust
let root = tree.get_root().unwrap();
let dists_to_root = tree
    .get_leaves()
    .iter()
    .map(|leaf_id| {
        tree.get_distance(leaf_id, &root)
            .map(|(l, _)| l.unwrap_or(0.))
        })
    .collect::<Result<Vec<_>, _>>()
    .unwrap();
```  

It is however fairly simple to write a memoized version of a function that would scale better: 

```rust
use anyhow::Context;
use phylotree::tree::Tree;

fn get_dist_to_root(tree: &Tree, node_id: usize, cache: &mut [Option<f64>]) -> anyhow::Result<f64> {
    if let Some(d) = cache[node_id] {
        // Check if we have already computed the value

        return Ok(d);
    } else if tree.get(&node_id)?.is_root() {
        // Check if current node is root

        cache[node_id] = Some(0.);
        return Ok(0.);
    }

    let node = tree.get(&node_id)?;
    let parent = node.parent.context("Missing Parent node")?;
    let mut d = node.parent_edge.context("Missing branch lengths")?;

    d += get_dist_to_root(tree, parent, cache)?;

    cache[node_id] = Some(d);
    Ok(d)
}

fn main() {
    let tree = tree::Tree::from_file(Path::new("./test.nwk")).unwrap();

    let mut cache = vec![None; tree.size()];
    let dists_to_root = tree
        .get_leaves()
        .iter()
        .map(|leaf_id| get_dist_to_root(&tree, *leaf_id, &mut cache))
        .collect::<Result<Vec<_>, _>>()
        .unwrap();
}
```

I tested these with a simulated $3\cdot10^6$ tip tree with exponential distribution branch lengths and on a single thread these distances are computed fairly fast for both versions: 

 - **Naive:** 800ms
 - **Memoized:** 220ms

I hope this helped but if you have any more questions or suggestions please don't hesitate to ask!

**Comment by jianshu93** [comment]
Hi @lucblassel Sorry for the late response, this is extremely helpful! As said above, I am now staring to working on the UniFrac project and combined it with annembed (https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=annembed&btnG=) to visualize millions of micorbiome samples. The key is to obtain a list of all branches (id, length of the branch), then for a feature table of a pair of samples, whether each sample has this branch  (looking at id only) by iterate all the features for that sample (the sample has many features that are tips of the tree) and then do some matrix operations based on the presence/absence of the feature for each sample and also the branch length. Is that possible to retrieve all branch length, id and then put them in a hashmap for quick lookup.  Happy to talk more about this topic. Another question is all tree options (e.g., remove a tip) is parallelized right? Thanks, Jianshu

**Comment by lucblassel** [comment]
Hi @jianshu93, No problem for the delay, I'm glad you're interested in this crate!  

Here are a couple of remarks that I think you might find useful: 

 1. As a general rule, any operation on the tree is not parallelized. However, since all the nodes are stored in a vector, if you know the index of the node you are interested in you can access it in constant time, without having to do any tree-traversal.  
This also means, by the way, that you could easily parallelize some operations on nodes by using a crate like [`rayon`](https://docs.rs/rayon/latest/rayon/index.html) on the `Node` iterator. 
 2. Regarding your data-structure, it seems to me that it should be possible to construct with the leaf-partition representation., where each edge of the tree is represented with a bitset where each bit represents a leaf, and the value of the bit represents the 2 sides of the bipartitions. This means that given an edge and 2 tips `i` and `j` you just need to check that the bits at positions `i` and `j` are different  *(i.e. XOR the bits)* to see if `i` and `j` are separated by that particular branch. 
 In the latest version of this crate _(not yet released on crates.io)_, there should be [a function](https://github.com/lucblassel/phylotree-rs/blob/6917675f360080debc3e5845c4081e6fe19590c1/src/tree/tree_impl.rs#L936) that gives you all the edge bipartitions with the corresponding edge lengths that you could probably use. 
 
I hope this helps you, but please do not hesitate to keep asking questions here, or you can contact me via email as well if you feel like collaborating a little more closely!

Thanks for using `phylotree`! 

Luc

**Comment by jianshu93** [comment]
Hi Luc, I send you an email. let me know if you did not get it. 
Best,
Jianshu
